# Generated by Django 5.0.2 on 2024-04-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_leavereportstudent_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('documentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(default=None, max_length=250, null=True, upload_to='tmp_ext/')),
                ('upload_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses')),
            ],
        ),
    ]
