# Generated by Django 5.0.2 on 2024-04-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_documentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
